### PR TITLE
Fix CI: Make new folder and copy everything into new folder

### PR DESCRIPTION
**Pull request by adam-fowler**

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Review by 0xTim — APPROVED** [review]
We're no longer running `npm compile` - is that deliberate?

**Comment by adam-fowler** [comment]
> We're no longer running `npm compile` - is that deliberate?

`npm run package` will do a compile so there is no need for the separate call.

**Pull request merged**
