### PR TITLE
Fix readonly document uri setup for Windows

### PR DESCRIPTION
**Pull request by adam-fowler**

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
Thanks!

**Comment by adam-fowler** [comment]
@compnerd have you verified this works?

**Comment by compnerd** [comment]
@adam-fowler yeah, I did test this and saw that we were able to get to the swift interface for the standard library interfaces from the goto declaration.

**Comment by adam-fowler** [comment]
Cool!

**Pull request merged**
