### PR TITLE
Fix typo (CodeLLDB)

### PR DESCRIPTION
**Pull request by kkk669**

### CODE REVIEW

**Review by 0xTim — CHANGES_REQUESTED** [review]
Oops thanks for this! One last change - in the project directory can you run `./scripts/generate_contributors_list.sh` to update the contributors list to make sure you're added! Thanks!

**Review by adam-fowler — APPROVED** [review]
Ha ha can't believe I kept calling it CoreLLDB

**Comment by kkk669** [comment]
@0xTim @adam-fowler Thank you for reviewing.

> Oops thanks for this! One last change - in the project directory can you run ./scripts/generate_contributors_list.sh to update the contributors list to make sure you're added! Thanks!

I've fixed it.

**Review by 0xTim — APPROVED** [review]
Thanks!

**Pull request merged**
