### PR TITLE
Add Update Dependencies button to Package Dependencies title bar

### PR DESCRIPTION
**Pull request by adam-fowler**
This is probably the operation I do the most often in relation to swift package manager, making it easy of access would be a good thing

I've included the package-lock.json as it has the wrong package name

### CODE REVIEW

**Comment by svanimpe** [comment]
Now that resolves happen automatically anyway, maybe we can just change that "Refresh" button to do an update instead of a resolve?

**Comment by adam-fowler** [comment]
I was going to suggest having a config option to enable/disable the automatic resolve. If you are working with large SPM projects it can be a pain.

**Comment by adam-fowler** [comment]
Another thing I think the package resolve is not working completely. In that it does unnecessary resolves. The resolve should only be triggered by a change in `Package.swift`. It seems to trigger on a change to `Package.resolved`.  I'll add an issue related to this.

**Comment by svanimpe** [comment]
The latter was intentional. @0xTim mentioned that users may pull in a newer version of Package.resolved, in which case there should be an additional `resolve`.

But it shouldn't be too hard to make both features optional.

**Comment by adam-fowler** [comment]
> The latter was intentional. @0xTim mentioned that users may pull in a newer version of Package.resolved, in which case there should be an additional resolve.
> 
> But it shouldn't be too hard to make both features optional.

That doesn't make sense `swift package resolve` updates the `Package.resolved` file. Why would you run it again if it has been updated by an external process. You can see this happen when you press the `swift package update` button, it runs an unnecessary resolve immediately after

**Comment by adam-fowler** [comment]
You will want to rebuild the package view based on changes to `Package.resolved`

**Review by 0xTim — APPROVED** [review]

**Comment by svanimpe** [comment]
Is it OK if I remove the Resolve button in favor of the Update button? Resolves should mostly happen automatically, so there shouldn't be a need for a button for it.

There's always the Resolve task should a user want to run it without opening a command line.

**Comment by 0xTim** [comment]
+1 from me

**Comment by adam-fowler** [comment]
> Is it OK if I remove the Resolve button in favor of the Update button? Resolves should mostly happen automatically, so there shouldn't be a need for a button for it.

done

**Review by svanimpe — APPROVED** [review]

**Pull request merged**
