### PR TITLE
Pass swift build arguments to sourcekit-lsp

### PR DESCRIPTION
**Pull request by adam-fowler**
This should resolve an issue where swift build needs to do a full rebuild all the time.

### CODE REVIEW

**Review by stevapple — CHANGES_REQUESTED** [review]
I don't think it's right to do this. Ideally SourceKit-LSP should accept the same arguments as SwiftPM, but it's completely not the case now. Passing valid SwiftPM flags to SourceKit-LSP could easily make it crashed.

**Comment by adam-fowler** [comment]
> I don't think it's right to do this. Ideally SourceKit-LSP should accept the same arguments as SwiftPM, but it's completely not the case now. Passing valid SwiftPM flags to SourceKit-LSP could easily make it crashed.

I asked @ahoppen who works on Sourcekit-LSP and he said it should be fine.

**Comment by stevapple** [comment]
> I asked @ahoppen who works on Sourcekit-LSP and he said it should be fine.

The first piece of difference I ran into is the missing support of build destination control in SK-LSP. I don’t know if there’s more, but doing this has much higher and more serious risks than you may think of.

**Comment by adam-fowler** [comment]
Are you saying if someone changes the build destination sourcekit lsp won't pick that up?

**Comment by stevapple** [comment]
> Are you saying if someone changes the build destination sourcekit lsp won't pick that up?

Worse: it will crash immediately (if we directly pass SwiftPM destination flags to it).

That’s why we must handle cross-compilation flags one by one through settings.

**Comment by adam-fowler** [comment]
Ok it looks like we can pass through `--build-path`, `-X...` family, as these should all be supported. If they aren't then that is a bug. The `--build-path` argument should eventually come from #283.

**Comment by adam-fowler** [comment]
@stevapple i added the argument filter. This should cover issue you brought up.

**Comment by stevapple** [comment]
For options we’re also supporting `--build-path=<path>` style. Can we add support for that too?🤔

**Comment by adam-fowler** [comment]
> For options we’re also supporting `--build-path=<path>` style. Can we add support for that too?🤔

Given we are eventually going to get the build path from a separate parameter maybe we can ignore this and remove it from here.

**Review by 0xTim — APPROVED** [review]
No objections on my part

**Comment by adam-fowler** [comment]
> > For options we’re also supporting `--build-path=<path>` style. Can we add support for that too?🤔
> 
> Given we are eventually going to get the build path from a separate parameter maybe we can ignore this and remove it from here.

Changed my mind and added support for `--build-path=<path>` style

**Pull request merged**
