### PR TITLE
Swift-5.8

### PR DESCRIPTION
**Pull request by adam-fowler**
Add CI docker-compose file for swift 5.8
Use Ubuntu 2204 for main branch swift

### CODE REVIEW

**Comment by adam-fowler** [comment]
Hi @tomerd , can you fix up the docker images for CI. To reflect the changes from above
cheers

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by adam-fowler** [comment]
@swift-server-bot test this please

**Comment by adam-fowler** [comment]
Reverted to using focal for the moment.

**Review by 0xTim — COMMENTED** [review]
Where are we referring to Ubuntu 22.04?

**Comment by adam-fowler** [comment]
> Where are we referring to Ubuntu 22.04?

Originally I had updated some of the docker images to use 2204 I thought, but it wasn't setup correctly. I decided I would move those changes to another PR and just use this one to add 5.8.

**Pull request merged**
