### PR TITLE
Fix failing SwiftExecution test

### PR DESCRIPTION
**Pull request by award999**
This "Build complete" string hasn't changed

### CODE REVIEW

**Comment by award999** [comment]
@swift-ci Please test

**Comment by award999** [comment]
@swift-server-bot test this please

**Comment by plemarquand** [comment]
@swift-server-bot add to allowlist

**Comment by adam-fowler** [comment]
@swift-server-bot add to allowlist

**Review by adam-fowler — APPROVED** [review]
Running a build makes the test last longer than expected, but I guess it is the process you'll be running this on.

**Pull request merged**
