### PR TITLE
Only set `target.sdk-path` if CodeLLDB setup Swift LLDB

### PR DESCRIPTION
**Pull request by adam-fowler**
If failed to setup CodeLLDB to use the Swift version of LLDB, then don't set setting specific to Swift LLDB. 
Also show error message when failing to setup CodeLLDB.

### CODE REVIEW

**Review by compnerd — COMMENTED** [review]
This seems like a safe change.  However, do we know why/when CodeLLDB fails to setup the path?  I think that it may currently never setup on Windows and requires the user to do that, this the message may want to direct the user towards the configuration.

**Comment by adam-fowler** [comment]
It does set it up at least that's what I've been led to believe. My situation was the swift lldb failed to start at all because it could not find python310.dll. Without this change you don't see it failed. 

When I started debugging tests I got the error, target.sdk_path is not a valid setting.

**Review by compnerd — APPROVED** [review]
SGTM

**Review by 0xTim — APPROVED** [review]
LGTM

**Pull request merged**
