### PR TITLE
Update soundness script and files without headers

### PR DESCRIPTION
**Pull request by adam-fowler**
Just realised we haven't been running the soundness script in CI.

@yim-lee can I have CI run the soundness script. There is a docker-compose `soundness` service which should trigger the script. Thank you

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Review by award999 — APPROVED** [review]
lgtm

**Comment by yim-lee** [comment]
@adam-fowler Added CI pipeline for soundness

**Comment by adam-fowler** [comment]
@yim-lee thank you

**Pull request merged**
