### PR TITLE
Add setting for disabling auto package resolve

### PR DESCRIPTION
**Pull request by adam-fowler**

### CODE REVIEW

**Comment by adam-fowler** [comment]
@swift-server-bot test this please

**Comment by fwcd** [comment]
I was just about to file an issue for this particular option when I saw this PR, very nice!

**Comment by adam-fowler** [comment]
> I was just about to file an issue for this particular option when I saw this PR, very nice!

Can I ask what issue you are seeing with the package resolve

**Comment by fwcd** [comment]
No particular issue, just a few minor annoyances, e.g.

- Swift package resolution occasionally hijacks my terminal, especially at startup
- Package resolution automatically makes network connections in the background, which sometimes isn't desirable
- Package resolution in the background sometimes causes race conditions, when a manual resolution is performed simultaneously e.g. from the terminal

In general, I prefer to do this manually (in other languages too), but can definitely see why people like the convenience of automatic resolution.

**Comment by adam-fowler** [comment]
The first two are known issues, the third one shouldn't be an issue as all swift operations for a workspace folder are queued to avoid them running on top of each other. 

Out of interest when it hijacks the terminal is it because the resolve failed.

**Comment by adam-fowler** [comment]
@swift-server-bot test this please

**Review by 0xTim — APPROVED** [review]

**Pull request merged**
